name: Build and Release .NET MAUI APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet workload install maui-android

    - name: Install dependencies
      run: dotnet restore

    - name: Extract version from tag
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          VERSION="1.0.1"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Using version $VERSION"

    - name: Build .NET MAUI project
      run: dotnet build -c Release /p:Version=${{ env.VERSION }}

    - name: Publish .NET MAUI Android project
      env:
        ANDROID_SIGN_KEY: ${{ secrets.ANDROID_SIGN_KEY }}
      run: dotnet publish -f net8.0-android -c Release -p:Version=${{ env.VERSION }} -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=$pwd\myapp.keystore -p:AndroidSigningKeyAlias=myapp -p:AndroidSigningKeyPass=$ANDROID_SIGN_KEY -p:AndroidSigningStorePass=$ANDROID_SIGN_KEY -p:AndroidSdkDirectory=$env:LOCALAPPDATA\Android\Sdk

    - name: Github
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ANDROID_SIGN_KEY: ${{ secrets.ANDROID_SIGN_KEY }}
      run: |
          gh release create ${{ github.ref }} ./output/*.apk --generate-notes
          