name: Build and Release .NET MAUI APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet workload install maui-android

    - name: Install dependencies
      run: dotnet restore

    - name: Build .NET MAUI project
      run: dotnet build -c Release

    - name: Publish .NET MAUI Android project
      run: dotnet publish NetMauiOptainiumHelloWorld -f:net8.0-android -c Release -o output

    - name: Github Prelease
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          gh release create ${{ github.ref }} ./output/*.apk --generate-notes
